# Generated by Django 5.2.5 on 2025-08-09 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('code', models.CharField(max_length=4, verbose_name='Код подтверждения')),
                ('temp_username', models.CharField(max_length=150, verbose_name='Временный логин')),
                ('temp_password', models.CharField(max_length=128, verbose_name='Временный пароль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('expires_at', models.DateTimeField(verbose_name='Время истечения')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
            ],
            options={
                'verbose_name': 'Код подтверждения Email',
                'verbose_name_plural': 'Коды подтверждения Email',
            },
        ),
    ]
